#ifndef RECORD_UTILS_H
#define RECORD_UTILS_H

#define MYSQL_BUF_SIZE 1024
#define MIN_TIME_STR_SIZE (19+1)
#define TIME_STR_BUF_SIZE 32
#define SEARCH_WORD_BUF_SIZE 512
#define SEARCH_ENGINE_ARRAY_SIZE 128
#define FULL_URL_BUF_SIZE 512
#define URL_BUF_SIZE 256
#define IP_BUF_SIZE 64
#define TRUE 1
#define FALSE 0

#endif

